server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learningPrint?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 此处设置为Asia/Shanghai 可解决从html date 到 mysql date  减一天的问题
    password: 
    username: root
  thymeleaf:
    cache: false
    mode: HTML5